# Generated by Django 5.2.5 on 2025-08-27 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Нотатка', 'verbose_name_plural': 'Нотатки'},
        ),
    ]
