# Generated by Django 5.2.5 on 2025-08-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Низький'), ('medium', 'Середній'), ('high', 'Високий'), ('urgent', 'Терміновий')], default='low', max_length=10, verbose_name='Приорітет'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('draft', 'Чернетка'), ('in_progress', 'В процесі'), ('completed', 'Завершено'), ('archived', 'Архів')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
